server:
  port: 56081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:56080/eureka

spring:
  datasource:
    ds0:
      url: jdbc:mysql://localhost:3306/bank1?useUnicode=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMills: 60000
      minEvictableIdleTimeMills: 300000
      validationQuery: SELECT user()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000

logging:
  level:
    root: INFO
    io:
      seata: debug
    org:
      springframework:
        cloud:
          alibaba:
            seata:
              web: debug