spring:
  application:
    name: dtx-txmsg-demo-bank1
  profiles:
    active: local
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  freemarker:
    enabled: true
    prefix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8

server:
  servlet:
    context-path: /bank1
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  use-forward-headers: true
